### ISSUE TITLE
'MESSAGE_DIR' is not recognized as an internal or external command - when running extract script

### ISSUE THREAD

**Issue by paunovic-stefan** [evenchange4/react-intl.macro#100]
I'm trying to use this in a react application created with CreateReactApplication

when running `npm run extract` i get the following error message
`'MESSAGE_DIR' is not recognized as an internal or external command`

package.json script is as follows

```json
"scripts": {
    "extract": "MESSAGE_DIR='./src/translations/extractedMessages' react-scripts build"
}
```

**Comment by oahmaro** [comment]
I have same issue, please help

**Comment by paunovic-stefan** [comment]
the problem was that the script is for Linux and Mac OSX... on windows the script needs to be modified to: `set MESSAGE_DIR='./src/translations/extractedMessages'&& react-scripts build`

or even better install cross-env npm module and modify the script to:
`cross-env MESSAGE_DIR='./src/translations/extractedMessages' react-scripts build` to be able to run on any OS

**Comment by pshadow** [comment]
I have to use
    set MESSAGE_DIR=./src/i18n/extractedMessages&&react-scripts build
on Windows.
