### ISSUE TITLE
ReferenceError: injectIntl is not defined

### ISSUE THREAD

**Issue by RopoMen** [evenchange4/react-intl.macro#39]
Another issue that I found is that `react-intl.macro` does not provide `injectIntl` method.

```
import React from 'react';
// import { defineMessages, injectIntl } from 'react-intl';
import { defineMessages, injectIntl } from 'react-intl.macro';

const messages = defineMessages({
    myMsg: {
        id: 'app.myMsg',
        defaultMessage: 'Hello!',
        description: 'Greeting'
    },
});

class MyComponent extends React.Component {
render() {return this.props.intl.formatMessage(messages.myMsg);}
}

export default injectIntl(MyComponent);
```

Edit: Improved example.

**Comment by evenchange4** [comment]
Does this help? Import two function separately:

> This use case is handled in test https://github.com/evenchange4/react-intl.macro/blob/master/src/__tests__/__snapshots__/macro.test.js.snap#L257-L289

```diff
import React from 'react';
+import { injectIntl } from 'react-intl';
+import { defineMessages } from 'react-intl.macro';

const messages = defineMessages({
    myMsg: {
        id: 'app.myMsg',
        defaultMessage: 'Hello!',
        description: 'Greeting'
    },
});

class MyComponent extends React.Component {
render() {return this.props.intl.formatMessage(messages.myMsg);}
}

export default injectIntl(MyComponent);
```

**Comment by evenchange4** [comment]
add docs to README.md

**Comment by RopoMen** [comment]
Hi,

I write my comment over here instead of making new ticket.

Thank you for providing this!

I'm not sure are you using create-react-app or not, but you should emphasize more why this macro should be used in Readme. This is much better than using `babel-plugin-react-intl`, because that would require making `eject` for your CRA.

I also tested that this package works fine with CRA without installing `babel-plugin-macros`.
