### ISSUE TITLE
Errors with untranspiled code in `intl-messageformat-parser`

### ISSUE THREAD

**Issue by MrToph** [evenchange4/react-intl.macro#84]
I'm using create-react-app with typescript and react-intl.

When running the build / extract script with imports from `react-intl` everything works fine.
As soon as I change it to `react-intl.macro` the scripts fail:

```
app/node_modules/babel-plugin-react-intl/lib/print-icu-message.js:6
import parser from 'intl-messageformat-parser';
       ^^^^^^

SyntaxError: Unexpected identifier
```

**Comment by jeffsheets** [comment]
I'm seeing the same error today after upgrading the Create React App react-scripts from 3.0.0 to 3.0.1. The error did not exist in react-scripts 3.0.0

**Comment by liemdo** [comment]
Mine doesn't work even after rolling back to 3.0.0.

**Comment by KyorCode** [comment]
Same problem here.

**Comment by wittlesouth** [comment]
Same here

**Comment by Anticom** [comment]
Changing the import to an ES5 import using `require` fixes it but i can't rely on patching my dependencies. There's an issue over at [`babel-plugin-react-intl`](https://github.com/formatjs/formatjs/issues/115) but i think the issue lies in this package.

**Comment by jeffsheets** [comment]
I was able to temporarily get around this by using a yarn resolution block like this:
```javascript
  "resolutions": {
    "react-intl.macro/babel-plugin-react-intl": "3.0.1"
  },
```

**Comment by juanghurtado** [comment]
Same problem here:

```
node_modules/babel-plugin-react-intl/lib/print-icu-message.js:6
import parser from 'intl-messageformat-parser';
       ^^^^^^

SyntaxError: Unexpected identifier

```

Any updates?

I'm not using yarn, so the resolution block is not an option to me. I know there are solutions like that for NPM, but I would prefer not to mess around to fix something that should be handled by the dependency itself.

**Comment by evenchange4** [comment]
The import issue should be fixed by https://github.com/evenchange4/react-intl.macro/commit/a7fa61192ef75bdfc61fc9db6a880329be7dc2e0 . Please try version `v0.3.7`.

**Comment by MrToph** [comment]
This solved the issue for me, thanks! @evenchange4
